AllCops:
  TargetRubyVersion: 2.7.6
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "bin/**"
    - "node_modules/**/*"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
# Style/RaiseArgs:
#   Enabled: false

# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: double_quotes

# Style/StringLiteralsInInterpolation:
#   Enabled: true
#   EnforcedStyle: double_quotes

# Layout/LineLength:
#   Max: 200

# Metrics/BlockLength:
#   Exclude:
#    - "spec/*"

# Metrics/MethodLength:
#   Max: 40
